Traceback (most recent call last):
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\salin\anaconda3\envs\book\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
X_new = np.linspace(0, 10, 1).reshape(-1,1)
softmax_reg.predict_proba(X)
#Probabilidad de pertencer a la clase cero
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Input [1;32mIn [28][0m, in [0;36m<cell line: 2>[1;34m()[0m
[0;32m      1[0m X_new [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m, [38;5;241m10[39m, [38;5;241m1[39m)[38;5;241m.[39mreshape([38;5;241m-[39m[38;5;241m1[39m,[38;5;241m1[39m)
[1;32m----> 2[0m [43msoftmax_reg[49m[38;5;241;43m.[39;49m[43mpredict_proba[49m[43m([49m[43mX[49m[43m)[49m

File [1;32m~\anaconda3\envs\book\lib\site-packages\sklearn\linear_model\_logistic.py:1672[0m, in [0;36mLogisticRegression.predict_proba[1;34m(self, X)[0m
[0;32m   1670[0m     [38;5;28;01mreturn[39;00m [38;5;28msuper[39m()[38;5;241m.[39m_predict_proba_lr(X)
[0;32m   1671[0m [38;5;28;01melse[39;00m:
[1;32m-> 1672[0m     decision [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdecision_function[49m[43m([49m[43mX[49m[43m)[49m
[0;32m   1673[0m     [38;5;28;01mif[39;00m decision[38;5;241m.[39mndim [38;5;241m==[39m [38;5;241m1[39m:
[0;32m   1674[0m         [38;5;66;03m# Workaround for multi_class="multinomial" and binary outcomes[39;00m
[0;32m   1675[0m         [38;5;66;03m# which requires softmax prediction with only a 1D decision.[39;00m
[0;32m   1676[0m         decision_2d [38;5;241m=[39m np[38;5;241m.[39mc_[[38;5;241m-[39mdecision, decision]

File [1;32m~\anaconda3\envs\book\lib\site-packages\sklearn\linear_model\_base.py:407[0m, in [0;36mLinearClassifierMixin.decision_function[1;34m(self, X)[0m
[0;32m    387[0m [38;5;124;03m"""[39;00m
[0;32m    388[0m [38;5;124;03mPredict confidence scores for samples.[39;00m
[0;32m    389[0m 
[1;32m   (...)[0m
[0;32m    403[0m [38;5;124;03m    this class would be predicted.[39;00m
[0;32m    404[0m [38;5;124;03m"""[39;00m
[0;32m    405[0m check_is_fitted([38;5;28mself[39m)
[1;32m--> 407[0m X [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_data[49m[43m([49m[43mX[49m[43m,[49m[43m [49m[43maccept_sparse[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mcsr[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mreset[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m
[0;32m    408[0m scores [38;5;241m=[39m safe_sparse_dot(X, [38;5;28mself[39m[38;5;241m.[39mcoef_[38;5;241m.[39mT, dense_output[38;5;241m=[39m[38;5;28;01mTrue[39;00m) [38;5;241m+[39m [38;5;28mself[39m[38;5;241m.[39mintercept_
[0;32m    409[0m [38;5;28;01mreturn[39;00m scores[38;5;241m.[39mravel() [38;5;28;01mif[39;00m scores[38;5;241m.[39mshape[[38;5;241m1[39m] [38;5;241m==[39m [38;5;241m1[39m [38;5;28;01melse[39;00m scores

File [1;32m~\anaconda3\envs\book\lib\site-packages\sklearn\base.py:585[0m, in [0;36mBaseEstimator._validate_data[1;34m(self, X, y, reset, validate_separately, **check_params)[0m
[0;32m    582[0m     out [38;5;241m=[39m X, y
[0;32m    584[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m no_val_X [38;5;129;01mand[39;00m check_params[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mensure_2d[39m[38;5;124m"[39m, [38;5;28;01mTrue[39;00m):
[1;32m--> 585[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_check_n_features[49m[43m([49m[43mX[49m[43m,[49m[43m [49m[43mreset[49m[38;5;241;43m=[39;49m[43mreset[49m[43m)[49m
[0;32m    587[0m [38;5;28;01mreturn[39;00m out

File [1;32m~\anaconda3\envs\book\lib\site-packages\sklearn\base.py:400[0m, in [0;36mBaseEstimator._check_n_features[1;34m(self, X, reset)[0m
[0;32m    397[0m     [38;5;28;01mreturn[39;00m
[0;32m    399[0m [38;5;28;01mif[39;00m n_features [38;5;241m!=[39m [38;5;28mself[39m[38;5;241m.[39mn_features_in_:
[1;32m--> 400[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    401[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mX has [39m[38;5;132;01m{[39;00mn_features[38;5;132;01m}[39;00m[38;5;124m features, but [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;124m"[39m
[0;32m    402[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mis expecting [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mn_features_in_[38;5;132;01m}[39;00m[38;5;124m features as input.[39m[38;5;124m"[39m
[0;32m    403[0m     )

[1;31mValueError[0m: X has 4 features, but LogisticRegression is expecting 1 features as input.
ValueError: X has 4 features, but LogisticRegression is expecting 1 features as input.

