Traceback (most recent call last):
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\salin\anaconda3\envs\book\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cost=[]
t_=[]
for i in range(0, 1000):
  h = linearRegresion(Theta_, X.T, N, 2)
  J = cost_function(h,y)  
  theta = gradD(h,Theta_, X,y, 0.1, N,2)  
  Theta_ = theta.T
  t_.append(theta[:1])
  cost.append(J)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [8][0m, in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      4[0m h [38;5;241m=[39m linearRegresion(Theta_, X[38;5;241m.[39mT, N, [38;5;241m2[39m)
[0;32m      5[0m J [38;5;241m=[39m cost_function(h,y)  
[1;32m----> 6[0m theta [38;5;241m=[39m [43mgradD[49m(h,Theta_, X,y, [38;5;241m0.1[39m, N,[38;5;241m2[39m)  
[0;32m      7[0m Theta_ [38;5;241m=[39m theta[38;5;241m.[39mT
[0;32m      8[0m t_[38;5;241m.[39mappend(theta[:[38;5;241m1[39m])

[1;31mNameError[0m: name 'gradD' is not defined
NameError: name 'gradD' is not defined

